# ============================================================
# Nombre del archivo : application.properties
# Ruta              : omcgc/backend/config/application.properties
# Tipo              : Configuración Externa (Runtime)
#
# Proyecto          : Sistema ERP en la nube para gestión de ópticas OMCGC
# Empresa           : WALOOK MEXICO, S.A. de C.V.
#
# Autor             : Gabriel Amílcar Cruz Canto
# Matrícula         : ES1821003109
# Programa          : Licenciatura en Ingeniería en Desarrollo de Software
# Unidad didáctica  : Proyecto Terminal I / Proyecto Terminal II
# Periodo académico : PT1 – PT2 (Agosto 2025 – Enero 2026)
#
# Versión           : v1.1
#
# Propósito:
# Definir parámetros de ejecución del servidor embebido Tomcat y redireccionar
# la estrategia de logging. Este archivo sobreescribe los defaults del JAR.
# ============================================================

server.port=9090
spring.application.name=omcgc-erp-backend

# Logging configuration
logging.config=file:./config/logback.xml
